name: learn-github-actions
on: [push]
env:
  globalval: gloval
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: nyan_env
    env:
      jobval: jobval
    steps:
      - uses: actions/checkout@v2
      - run: pwd && git status && ls -Al && echo $globalval $jobval $stepval $ENV_SEC_NYAN
        env:
          stepval: stepval
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hello-artifact
          path: .
  job2:
    runs-on: ubuntu-latest
    environment: wanw_env
    env:
      jobval: jobval
    steps:
      - uses: actions/checkout@v2
      - run: pwd && git status && ls -Al && echo $globalval $jobval $stepval $WANW_ENV_FOO
